---
- name: Deploy a jar file
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Deploy Army
      docker_container:
        name: calculator_container
        image: vib123/calculator_mini_project:ver1
        state: present
