---
- name: Deploy a jar file
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Deploy Army
      docker_container:
        name: shop_container
        image: vib123/spe_major_backend:ver1
        state: present
